apiVersion: v1
kind: Service
metadata:
  name: codebase-architect-frontend
  namespace: codebase-architect
  labels:
    app: codebase-architect
    component: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: codebase-architect
    component: frontend
  sessionAffinity: None
